### ISSUE TITLE
Issues installing through the README file

### ISSUE THREAD

**Issue by l0rd** [raffaelespazzoli/backstage-demo#7]
- `s/Oauth app in this organization for Code Ready Workspaces/Oauth app in this organization for Eclipse Che/g`
- We could link [to the documentation](https://github.com/martinbaillie/vault-plugin-secrets-github#setup-github) in step 8 ("create a GitHub Application for the vault-config-operator")
- `s/create and account/create an account/g`
- `secrets.sh` has some quay info but in the steps above there is no quay instructions. Maybe there is a step missing to [create a quay token](https://docs.quay.io/api/)? But anyway what accesses are needed by the quay token?
-  In `secrets.sh` the variable `cockroachdb_key=<service_account_name>` should have the "API Key ID" or the "API Key Name"?
- Fork + clone of `https://github.com/raffaelespazzoli/backstage-demo` should happen at the very beginning, before we start editing `secrets.sh` at least.
- Running `find . -type f -not -path '*/\.git/*' -exec sed -i "s/raffaelespazzoli/${github_organization}/g" {} +` I got the error `sed: 1: "./secrets.sh": invalid command code .` (on macos `gnu-sed` is required)
- We should mention to connect to https://openshift-gitops-server-openshift-gitops.apps.${base_domain} to check apps deployment and re-synch
- After a few hours setting all up I figured out that my cluster doesnt' have enough resources, maybe we should mention a typical cluster where this demo is supposed to work? Mine has 3 worker nodes of type m6i.large (2 vCPU and 8GB or RAM each) and some pods failed to install because there were no available nodes.

**Comment by raffaelespazzoli** [comment]
all of these comments have been addressed, with the exception of the mac specific one. Thanks for pointing them out.

**Comment by l0rd** [comment]
👍 

> minimum worker node size 16GB 4CPUs (needed for eclipse che)

This is kind of ironic as I can definitely install eclipse che + run development workspaces on a cluster that's half the size of it but I cannot install the backstage demo on the same cluster (not even trying to run a dev workspace).
